on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [main, "release/*"] # include release branches like release/1.0.x
  pull_request:
    branches: [main, "release/*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.6, 3.7, 3.8, 3.9]
        cuda_version: [11.2.2, 11.1, 10.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.cuda_version }}-${{ matrix.python_version }}-
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: justusschock/cuda-conda-python:${{ matrix.cuda_version }}-${{ matrix.python_version }}
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            PYTHON_VERSION=${{ matrix.python_version }}

          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
